### ISSUE TITLE
How to ban if AUTH_USERS is channel ?

### ISSUE THREAD

**Issue by ranmiella** [SpEcHiDe/NoPMsBot#10]

**Comment by SpEcHiDe** [comment]
Reply BAN_COMMAND, I guess.

**Comment by ranmiella** [comment]
not work, i set AUTH_USERS: -1001389422871  ( is channel id) . so all msg will be forward to channel. i try to reply ban on channel / ban. but not work.  i need it because some people can spam on my channel.

**Comment by ranmiella** [comment]
THANKS
