### ISSUE TITLE
FEATURE REQUEST: AWAY FROM KEYBOARD (AFK) MODE

### ISSUE THREAD

**Issue by Mikesew1320** [SpEcHiDe/NoPMsBot#12]
Can you add ability to leave set message for peoples who send messages when we are offline? Like .afk [myreason]

**Comment by hvydya** [comment]
Hi! I'd like to work on this issue. Can you assign it to me?

**Comment by SpEcHiDe** [comment]
closing this, since this is a duplicate of #14

@hvydya you can PR your changes when it is completed.
