### ISSUE TITLE
Help on install the bot

### ISSUE THREAD

**Issue by Deltwin** [SpEcHiDe/NoPMsBot#24]
how i can install the bot?
i

**Comment by SpEcHiDe** [comment]
Read the README.

Readme => Read + me => Mujhe Padhe => मुझे पढ़ => مجھے پڑھیں => මාව කියවන්න => నన్ను చదువు => എന്നെ വായിക്കുക => আমাকে পড়ুন => ನನ್ನನ್ನು ಓದಿ 🥺

**Comment by Deltwin** [comment]
ok thank you!

**Comment by Deltwin** [comment]
btw i'm english

**Comment by Deltwin** [comment]
wait in the readme there is nothing about start the bot

**Comment by SpEcHiDe** [comment]
read the res directory contents, ☹️☹️😬

**Comment by Deltwin** [comment]
ye ye ye thanks!
