### ISSUE TITLE
remove forwarded_from user, use buttons in Telegram ..!

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/NoPMsBot#4]

**Comment by SpEcHiDe** [comment]
https://t.me/ThankTelegram/690162 hmmm

**Comment by ranmiella** [comment]
fwded_mesg = await message.forward(
        AUTH_CHANNEL, as_copy=True
    )

i just add as_copy=true at file on_pm_message and its work

**Comment by SpEcHiDe** [comment]
this is no longer possible because of #29
